# Generated by Django 6.0.1 on 2026-02-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_status_alter_users_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='states',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
